HW 35 Polina
jathpr/FE42Bloc3 pull request #17
Opened 2023-04-07 10:02 UTC by polishukova

2023-04-07 10:05 UTC, polishukova commented
I don't know, why is older commits here..

2023-04-08 06:33 UTC, jathpr commented on hw-35.ts
> +    return carsArr.length
wrong

2023-04-08 06:35 UTC, jathpr commented on hw-35.ts
> +    const usersArr = users.filter(user => user.animals)
potentially you can check empty array case too

2023-04-08 06:37 UTC, jathpr commented on hw-35.ts
> +    const carStr = carArr.join (',')
looks like it would be an array of arrays, not an array of strings
you can try to use Set here possible with reduce

2023-04-08 06:37 UTC, jathpr requested changes
time to fix git has come)
hw looks good for me

2023-04-09 16:13 UTC, closed without merging